@startuml sbags-class

interface Game {
    +getGameState(): GameState
    +executeMove(move: Move): GameState
}

interface Move {
    +execute(state: GameState): GameState
}

interface GameState {
    +getBoard(): Board
}

GameState <.right. Move
Game ..> Move
Game o-- GameState


@enduml