@startuml gui_sequence

participant GameView as V
participant GameController as C
participant Game as M

'skinparam BoxPadding 2

loop !game ended
    V ->> V: wait(event)
    V -> C: notify(event)
    C -> C: store(event)
    alt events match move
        C -> M: executeMove(move)
        alt valid move
            M --> C: Right(gameState)
            C -> V: moveAccepted(gameState)
        else
            M --> C: Left(failure)
            C -> V: moveRejected(failure)
        end
        C -> C: clearEvents()
    end
end 
@enduml